/**
 * Anchored levels — pre-placed, permanently locked pieces on the main path.
 *
 * WHAT THE PLAYER SEES
 * --------------------
 * One to three of the level's pieces are already on the board when it opens,
 * rendered with a solid full-colour locked skin (inset rim and padlock) and
 * refusing every drag. The rest of the puzzle is solved around that skeleton.
 *
 * WHY IT EXISTS
 * -------------
 * Difficulty in this game is the number of distinct exact-cover packings, and
 * two measured facts box in the alternatives (docs/experiments/tangram-pack/):
 * more pieces makes a board EASIER, and a solid-cell partition cannot be both
 * many-piece and tight. Locking pieces removes packings without adding a single
 * diagonal split, so the board keeps looking like the colour-mixing game it is.
 * The previous difficulty attempt raised diagonal density instead and was
 * rejected on playtest for exactly that reason.
 *
 * WHERE THE DATA LIVES
 * --------------------
 * js/anchoredLevels.js, generated by scripts/build-anchored.mjs. Deliberately
 * NOT js/levels.js: that file is rewritten wholesale by build-world-pack.mjs
 * and any content placed there would be silently destroyed.
 *
 * CADENCE AND THE EXCLUSION CHAIN
 * -------------------------------
 * Anchored takes position 4 of every chapter from chapter 2 on (idx 14, 24,
 * 34, ...). That slot is 'med' tier in all 100 chapters and is never Prism and
 * never Frost, so Treasure is the only type that can contest it — which happens
 * once every 90 levels, when idx % 9 === 6 coincides.
 *
 * Anchored yields to all three. It is the newest type, and Treasure's
 * "chest in N levels" nudge depends on an unbroken interval, so Anchored is the
 * one that steps aside. The chain is therefore:
 *
 *     Prism (authored)  >  Frost  >  Treasure  >  Anchored
 *
 * The former Pulse slots are free (Pulse is disabled, js/pulse.js), so nothing
 * here has to reason about it.
 *
 * A level is only Anchored if the cadence matches AND js/anchoredLevels.js
 * actually carries an entry for that index. That is what keeps this batch to
 * the 30 authored levels instead of silently claiming all 88 free slots with
 * nothing to serve.
 */

import { ANCHORED_LEVELS, ANCHORED_FIRST_LEVEL, ANCHORED_INTERVAL } from './anchoredLevels.js?v=3bd14eb0045c';
import { LEVEL_META, CHAPTER_SIZE } from './levels.js?v=3bd14eb0045c';
import { isTreasureLevel } from './treasure.js?v=3bd14eb0045c';

export { ANCHORED_FIRST_LEVEL, ANCHORED_INTERVAL };

// Mirrors game.js / treasure.js / pulse.js. Duplicated by convention in all
// four — change one, change all, or the special types start overlapping.
const FROST_MIN_LEVEL = 30;

const BY_INDEX = new Map(ANCHORED_LEVELS.map(lv => [lv.index, lv]));

export const matchesAnchoredCadence = (idx) =>
    Number.isInteger(idx)
    && idx >= ANCHORED_FIRST_LEVEL
    && (idx - ANCHORED_FIRST_LEVEL) % ANCHORED_INTERVAL === 0;

/**
 * True when `idx` is an Anchored level. Mode-agnostic on purpose — game.js
 * gates on `gameMode === 'normal'` at the call site, the same way isFrostLevel
 * does, so Daily and Tutorial keep serving the shipped grid for that index.
 */
export const isAnchoredLevel = (idx) => {
    if (!matchesAnchoredCadence(idx)) return false;
    if (!BY_INDEX.has(idx)) return false;
    const meta = LEVEL_META[idx] || {};
    if (meta.kind === 'prism') return false;
    if (meta.tier === 'shape' && idx >= FROST_MIN_LEVEL) return false;
    if (isTreasureLevel(idx)) return false;
    // Redundant with the Prism check today (every finale is a prism-finale),
    // kept as an explicit invariant so the property does not depend on a
    // generator convention a future pack rebuild could quietly drop.
    if (idx % CHAPTER_SIZE === CHAPTER_SIZE - 1) return false;
    return true;
};

/** The Anchored level record for `idx`, or null. */
export const getAnchoredLevel = (idx) => (isAnchoredLevel(idx) ? BY_INDEX.get(idx) : null);

/**
 * The grid the game should load for `idx` — the Anchored replacement when one
 * applies, otherwise null and the caller falls back to LEVELS[idx].
 *
 * Used by js/game.js loadLevel and by js/ui/screens.js, so the level-intro card
 * reports the grid the player is actually about to see rather than the shipped
 * one it replaces.
 */
export const getAnchoredGrid = (idx) => getAnchoredLevel(idx)?.grid || null;

export const nextAnchoredIn = (fromIdx) => {
    for (let i = 0; i <= ANCHORED_INTERVAL * 3; i++) {
        if (isAnchoredLevel(fromIdx + i)) return i;
    }
    return -1;
};

export default { isAnchoredLevel, getAnchoredLevel, getAnchoredGrid, nextAnchoredIn };
